.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, README.md, cypress.json
- badge for codecov
- support in CI for cypress
- badge for cypress
=> Badge for Codecov

package-lock.json, package.json, src/components/Items/Header.vue, src/components/UI/Buttons/IconButton.vue, src/views/Player.vue
Why Composition API?
- can selectively expose whatever variables and functions we need access to in the HTML area (in the options API, all methods that are declared are exposed)
- makes reusing code much much neater - one has to hack around things in the options API and it is very messy
- very good typescript support compared to the options API
=> Switches to Composition API

.github/workflows/deploy_to_s3_prod.yml, .github/workflows/deploy_to_s3_staging.yml, package.json
=> Adds deployment pipeline for staging and production 

package-lock.json, package.json, src/components/Splash.vue, tests/e2e/specs/renders-player.js, tests/unit/components/Splash.spec.ts
Fixes #13 
- Wrote tests for splash.vue.
=> Added tests

src/components/Splash.vue, src/components/UI/Icons/Splash.vue, src/views/Player.vue, tests/unit/components/Questions/QuestionModal.spec.ts, tests/unit/components/Splash.spec.ts
=> loading spinner on main screen + on button + disabled button in starting

src/components/Questions/Header.vue, src/components/Questions/QuestionModal.vue
Removed click-away and closing question palette only about clicking the hamburger or one of the question boxes.
=> Fixes click-away bug on question palette hamburger

src/components/Questions/Body.vue, src/components/Questions/QuestionModal.vue
=> Updated the placeholder

README.md
- Adds instruction to specify `apiKey` in quiz URL
- [] ~Test Responsiveness~
- [] ~Cross-Browser Testing~
- [] ~Hygiene and Housekeeping~
- [] ~Testing~
- [] ~Lighthouse Checks~
=> adds apikey instruction to readme

src/components/Scorecard.vue
Changes `Go Back` text on Scorecard screen to `See Answers`
- [~] Wrote tests
=> Minor: changes `Go Back` to `See Answers`

src/components/Questions/Body.vue, src/components/Questions/Footer.vue, src/components/Questions/QuestionModal.vue, src/components/Scorecard.vue, src/components/UI/Text/Textarea.vue, src/services/API/Quiz.ts, src/types.ts, tests/e2e/fixtures/assessment_quiz.json, tests/e2e/fixtures/new_session.json, tests/e2e/fixtures/resume_session.json, tests/e2e/specs/renders-player-assessment.js, tests/unit/components/Questions/Body.spec.ts
Fixes #53 -- small change in `Footer.vue` 
Fixes #64 , #65  -- Errors in numerical text area
Fixes #66 
- Fixed minor bugs
- Removed gray color display for options before quiz submission. Gray color is used only for ungraded questions to indicate the selected answer *post* quiz submission.
- Updated tests accordingly.
=> Numerical and Clear/Previous button fixes

src/components/Questions/Body.vue, src/types.ts, tests/e2e/specs/renders-player-assessment.js
Fixes #81 
- Adds question number information at the top of question text (matching NTA)
- Adds relevant tests
TODO
- Add question set name / question type information too
- Have to improve CSS
=> Add question number to Body

src/components/Questions/Header.vue, src/components/Questions/QuestionModal.vue, src/components/Scorecard.vue, src/views/FormInput.vue, tests/e2e/specs/renders-player-assessment.js, tests/e2e/specs/renders-player-to-check-timed.js, tests/unit/components/Questions/Header.spec.ts, tests/unit/components/Questions/QuestionModal.spec.ts
1. Adds text instructions to form page.
2. Adds additional click requirement for end test button (changes tests accordingly).
3. Removes See Answers, Share buttons on Scorecard
4. Removes unnecessary fields in form
5. Adds month, day, year as separate dropdowns in form
6. Changes userid creation process 
(Ideally revert most of these changes after JNV test is done -- mostly average to bad code)
=> Adds instructions to form page

src/views/FormInput.vue
=> Adds new instruction

src/components/Questions/QuestionModal.vue, src/components/Scorecard.vue, src/types.ts, src/views/FormInput.vue, src/views/Player.vue, tests/e2e/specs/renders-player-assessment.js, tests/e2e/specs/renders-player-to-check-timed.js, tests/unit/components/Questions/QuestionModal.spec.ts
1. Retains Share button
2. Removes additional toast for endtest
3. Removes dummy-event (added this for timer)
=> Reverting changes made to quiz

src/router/index.ts, src/services/API/FormInputHandling.ts, src/types.ts, src/views/FormResults.vue
1. Adds results form at /jnvenablereports
2. Idea is to check if quiz-data and form-data exist, and display link to reporting engine page.
3. There are several cases to deal with here -- data exists in one place and not in other.
4. Also have to handle ENF results. 
How it works?
- send request to Form lambda with resultsQuery = true;
- if response asks for redirecting to get form data filled -- display additional form fields
=> Adds results form

src/services/Functional/Utilities.ts
=> subset pattern bug fix, added some null checks for homework quizzes less than 10 questions

src/services/API/Session.ts, src/views/Player.vue, tests/e2e/specs/renders-player-assessment.js, tests/e2e/specs/renders-player-to-check-optional.js, tests/e2e/specs/renders-player-to-check-timed.js
Backend PR - https://github.com/avantifellows/quiz-backend/pull/84
Additional edit by @suryabulusu : Solves Issue #104
=> Respective frontend changes for backend optimizations. See the linked PR

.github/workflows/ci.yml, src/views/Player.vue, tests/e2e/specs/renders-player-assessment.js
Small PR to solve #105 
We trigger `endTest()` when the last question in homework player is submitted (and the test hasn't already ended yet)
=> End Test for Homeworks too

src/services/Functional/Utilities.ts, src/types.ts, src/views/Player.vue
Temp partial marking for multiple answers. If chosen answer is a proper subset of correct answer, award `len(chosen_answer)` as a partial score
=> partial marks initial exp

src/types.ts, src/views/Player.vue
Small change to variable name -- from `always_review_answers` to `review_immediate`
=> changes review var name

src/index.css
Small change to use more width in tables
=> Changes table css

src/components/LandingPage.vue, src/router/index.ts
Fixes #111 
- Made a basic Landing Page
=> Home Page for Quiz Engine

src/components/Scorecard.vue, src/types.ts, src/views/Player.vue
Small commit to display a table of question set metrics
=> adds subject wise table to scorecard

src/components/Questions/Body.vue, src/components/Scorecard.vue, src/components/Splash.vue, src/types.ts
- Display "characters left" for subjective questions
- Do not display instructions for homework
- Do not display attempt/accuracy rate table in scorecard for homework
=> Minor UI fixes

src/components/Questions/Body.vue
Small bug: Display solutions for homework immediately after question is answered
=> Small bug: Display solutions for homework 

src/services/Functional/Utilities.ts, src/views/Player.vue
Small changes to depict correct number of questions in each set (remove non-graded questions from total questions count). This helps in arriving at correct accuracy rate.
=> Improves Non Graded Question calculations

.github/ISSUE_TEMPLATE/DMP_2024.yml, README.md
Running command `npm run build --mode staging` for staging was throwing error - `Module not found: Error: Can't resolve '<Project path>\staging'`.
Corrected it using reference - [https://stackoverflow.com/a/54786708/4029542](url)
=> Corrected staging command in readme

.gitignore, src/components/Omr/OmrItem.vue, src/components/Omr/OmrModal.vue, src/components/Questions/Body.vue, src/components/Questions/Footer.vue, src/components/Questions/Header.vue, src/components/Questions/Palette/Item.vue, src/components/Questions/Palette/KeyTemplate.vue, src/components/Questions/Palette/QuestionPalette.vue, src/components/Questions/QuestionModal.vue, src/components/UI/Buttons/IconButton.vue, src/components/UI/Progress/CircularProgress.vue, src/components/UI/Text/InputText.vue, src/components/UI/Text/Textarea.vue, src/services/API/FormInputHandling.ts, src/services/API/Organization.ts, src/services/API/Question.ts, src/services/API/Quiz.ts, src/services/API/Session.ts, src/services/Functional/Utilities.ts, tsconfig.json, vue.config.js
=> added direct routing
